spring.application.name=social
server.port=3001

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/social_users
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# MongoDB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration# Liquibase
spring.jpa.hibernate.ddl-auto=none

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/001_create_users.sql



server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false
# true ??? HTTPS